version: '3.3'
services:
  bucky-core:
    image: lifullsetg/bucky-core:0.9.22
    container_name: bucky-core
    networks:
      bucky:
    volumes:
      - ./sample:/app
    tty: true
    environment:
      - BUCKY_DB_USERNAME=root
      - BUCKY_DB_PASSWORD=password
      - BUCKY_DB_HOSTNAME=bm-mysql
      - BUCKY_DB_NAME=bucky_development
      - BUCKY_FQDN=http://bm-web
  chrome:
    image: selenium/standalone-chrome-debug:3.141.59-oxygen
    container_name: chrome
    ports:
      - '4444:4444'
      - '5901:5900'
    shm_size: 1G
    networks:
      bucky:
networks:
  bucky:
    external: true